export const commands = [
  {
    label: "call",
    value: "call",
    args: [
      {
        name: "CANISTER_NAME",
        placeholder: "Enter canister name/id",
        optional: false,
      },
      {
        name: "METHOD_NAME",
        placeholder: "Enter method name",
        optional: false,
      },
      { name: "ARGUMENT", placeholder: "Enter argument", optional: true },
    ],
    options: [
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--type",
        placeholder: "idl",
        type: "argument",
        description: "Specifies the data type for the argument when making the call",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--argument-file",
        placeholder: "path/to/file",
        type: "argument",
        description: "Specifies the file from which to read the argument to pass to the method",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--async",
        type: "flag",
        description: "Specifies not to wait for the result of the call to be returned by polling the replica",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--query",
        type: "flag",
        description: "Sends a query request to a canister instead of an update request",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--update",
        type: "flag",
        description: "Sends an update request to a canister. This is the default if the method is not a query method",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
      {
        name: "--random",
        placeholder: "Config for random argument",
        type: "argument",
        description: "Specifies the config for generating random argument",
      },
      {
        name: "--output",
        placeholder: "idl",
        type: "argument",
        description: "Specifies the format for displaying the method's return result",
      },
      {
        name: "--with-cycles",
        placeholder: "Amount of cycles",
        type: "argument",
        description: "Specifies the amount of cycles to send on the call. Deducted from the wallet",
      },
      {
        name: "--candid",
        placeholder: "path/to/file.did",
        type: "argument",
        description: "Provide the .did file with which to decode the response",
      },
      {
        name: "--always-assist",
        type: "flag",
        description: "Always use Candid assist when the argument types are all optional",
      },
      {
        name: "--impersonate",
        placeholder: "Principal",
        type: "argument",
        description: "Send request on behalf of the specified principal. This option only works for a local PocketIC instance",
      },
    ],
  },
  {
    label: "create",
    value: "create",
    args: [
      {
        name: "CANISTER_NAME",
        placeholder: "Enter canister name",
        optional: true,
      },
    ],
    options: [
      {
        name: "--all",
        type: "flag",
        description: "Creates all canisters configured in dfx.json",
      },
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--with-cycles",
        placeholder: "Amount of cycles",
        type: "argument",
        description: "Specifies the initial cycle balance to deposit into the newly created canister",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--specified-id",
        placeholder: "Principal",
        type: "argument",
        description: "Attempts to create the canister with this Canister ID",
      },
      {
        name: "--controller",
        placeholder: "Identity name or principal",
        type: "argument",
        description: "Specifies the identity name or the principal of the new controller",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--compute-allocation",
        placeholder: "0-100",
        type: "argument",
        description: "Specifies the canister's compute allocation. This should be a percent in the range [0..100]",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--memory-allocation",
        placeholder: "0-12 GiB",
        type: "argument",
        description: "Specifies how much memory the canister is allowed to use in total",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
      {
        name: "--wasm-memory-threshold",
        placeholder: "Bytes",
        type: "argument",
        description: "Specifies a threshold on the Wasm memory usage of the canister",
      },
      {
        name: "--log-visibility",
        placeholder: "controllers|public",
        type: "argument",
        description: "Specifies who is allowed to read the canister's logs",
      },
      {
        name: "--log-viewer",
        placeholder: "Principal",
        type: "argument",
        description: "Specifies the principal of the log viewer of the canister",
      },
      {
        name: "--no-wallet",
        type: "flag",
        description: "Performs the call with the user Identity as the Sender of messages",
      },
      {
        name: "--created-at-time",
        placeholder: "Nanoseconds",
        type: "argument",
        description: "Transaction timestamp, in nanoseconds, for use in controlling transaction deduplication",
      },
      {
        name: "--from-subaccount",
        placeholder: "Subaccount",
        type: "argument",
        description: "Subaccount of the selected identity to spend cycles from",
      },
      {
        name: "--subnet-type",
        placeholder: "Subnet type",
        type: "argument",
        description: "Specify the optional subnet type to create canisters on",
      },
      {
        name: "--subnet",
        placeholder: "Subnet",
        type: "argument",
        description: "Specify a specific subnet on which to create canisters on",
      },
      {
        name: "--next-to",
        placeholder: "Canister ID",
        type: "argument",
        description: "Create canisters on the same subnet as this canister",
      },
    ],
  },
  {
    label: "delete",
    value: "delete",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: true,
      },
    ],
    options: [
      {
        name: "--all",
        type: "flag",
        description: "Deletes all of the canisters configured in the dfx.json file",
      },
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--no-withdrawal",
        type: "flag",
        description: "Do not withdrawal cycles, just delete the canister",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--withdraw-cycles-to-canister",
        placeholder: "Canister/Wallet ID",
        type: "argument",
        description: "Withdraw cycles from canister(s) to the specified canister/wallet before deleting",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--withdraw-cycles-to-dank",
        type: "flag",
        description: "Withdraw cycles to dank with the current principal",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--withdraw-cycles-to-dank-principal",
        placeholder: "Principal ID",
        type: "argument",
        description: "Withdraw cycles to dank with the given principal",
      },
      {
        name: "--initial-margin",
        placeholder: "Amount",
        type: "argument",
        description: "Leave this many cycles in the canister when withdrawing cycles",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
      {
        name: "--yes",
        type: "flag",
        description: "Auto-confirm deletion for a non-stopped canister",
      },
      {
        name: "--to-subaccount",
        placeholder: "Subaccount",
        type: "argument",
        description: "Subaccount of the selected identity to deposit cycles to",
      },
    ],
  },
  {
    label: "deposit-cycles",
    value: "deposit-cycles",
    args: [
      {
        name: "CYCLES",
        placeholder: "Enter amount of cycles",
        optional: false,
      },
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: true,
      },
    ],
    options: [
      {
        name: "--all",
        type: "flag",
        description: "Deposit cycles to all of the canisters configured in the dfx.json file",
      },
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--from-subaccount",
        placeholder: "Subaccount",
        type: "argument",
        description: "Use cycles from this subaccount",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--created-at-time",
        placeholder: "Nanoseconds",
        type: "argument",
        description: "Transaction timestamp, in nanoseconds, for use in controlling transaction deduplication",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "id",
    value: "id",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name",
        optional: false,
      },
    ],
    options: [
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "info",
    value: "info",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: false,
      },
    ],
    options: [
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "install",
    value: "install",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: true,
      },
      {
        name: "OUTPUT_ENV_FILE",
        placeholder: "Enter output env file path",
        optional: true,
      },
    ],
    options: [
      {
        name: "--all",
        type: "flag",
        description: "Deploys all canisters configured in the project dfx.json files",
      },
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--async-call",
        type: "flag",
        description: "Specifies not to wait for the result of the call to be returned by polling the replica. Instead return a response ID",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--mode",
        placeholder: "install",
        type: "argument",
        description: "Specifies the mode of canister installation",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--skip-pre-upgrade",
        type: "flag",
        description: "Skip the pre_upgrade hook on upgrade",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--wasm-memory-persistence",
        placeholder: "keep",
        type: "argument",
        description: "Keep or replace the Wasm main memory on upgrade",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
      {
        name: "--upgrade-unchanged",
        type: "flag",
        description: "Upgrade the canister even if the .wasm did not change",
      },
      {
        name: "--argument",
        placeholder: "Argument",
        type: "argument",
        description: "Specifies the argument to pass to the method",
      },
      {
        name: "--argument-type",
        placeholder: "idl",
        type: "argument",
        description: "Specifies the data type for the argument when making the call using an argument",
      },
      {
        name: "--argument-file",
        placeholder: "path/to/file",
        type: "argument",
        description: "Specifies the file from which to read the argument to pass to the method",
      },
      {
        name: "--wasm",
        placeholder: "path/to/file.wasm",
        type: "argument",
        description: "Specifies a particular Wasm file to install, bypassing the dfx.json project settings",
      },
      {
        name: "--yes",
        type: "flag",
        description: "Skips yes/no checks by answering 'yes'. Such checks usually result in data loss, so this is not recommended outside of CI",
      },
      {
        name: "--no-asset-upgrade",
        type: "flag",
        description: "Skips upgrading the asset canister, to only install the assets themselves",
      },
      {
        name: "--always-assist",
        type: "flag",
        description: "Always use Candid assist when the argument types are all optional",
      },
    ],
  },
  {
    label: "metadata",
    value: "metadata",
    args: [
      {
        name: "CANISTER_NAME",
        placeholder: "Enter canister name/id",
        optional: false,
      },
      {
        name: "METADATA_NAME",
        placeholder: "Enter metadata name",
        optional: false,
      },
    ],
    options: [
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "request-status",
    value: "request-status",
    args: [
      {
        name: "REQUEST_ID",
        placeholder: "Enter request ID (0x...)",
        optional: false,
      },
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: false,
      },
    ],
    options: [
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--output",
        placeholder: "idl",
        type: "argument",
        description: "Specifies the format for displaying the method's return result",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "send",
    value: "send",
    args: [
      {
        name: "FILE_NAME",
        placeholder: "Enter message file name",
        optional: false,
      },
    ],
    options: [
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--status",
        type: "flag",
        description: "Send the signed request-status call in the message",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "sign",
    value: "sign",
    args: [
      {
        name: "CANISTER_NAME",
        placeholder: "Enter canister name/id",
        optional: false,
      },
      {
        name: "METHOD_NAME",
        placeholder: "Enter method name",
        optional: false,
      },
      {
        name: "ARGUMENT",
        placeholder: "Enter argument",
        optional: true,
      },
    ],
    options: [
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--type",
        placeholder: "idl",
        type: "argument",
        description: "Specifies the data type for the argument when making the call using an argument",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--argument-file",
        placeholder: "path/to/file",
        type: "argument",
        description: "Specifies the file from which to read the argument to pass to the method",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--query",
        type: "flag",
        description: "Sends a query request to a canister",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--update",
        type: "flag",
        description: "Sends an update request to a canister. This is the default if the method is not a query method",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--random",
        placeholder: "Config for random argument",
        type: "argument",
        description: "Specifies the config for generating random argument",
      },
      {
        name: "--expire-after",
        placeholder: "5m",
        type: "argument",
        description: "Specifies how long the message will be valid in seconds, default to be 300s (5 minutes)",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
      {
        name: "--file",
        placeholder: "message.json",
        type: "argument",
        description: "Specifies the output file name",
      },
      {
        name: "--always-assist",
        type: "flag",
        description: "Always use Candid assist when the argument types are all optional",
      },
    ],
  },
  {
    label: "snapshot",
    value: "snapshot",
    args: [
      {
        name: "SUBCOMMAND",
        placeholder: "create|load|list|delete",
        optional: false,
      },
    ],
    options: [
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "start",
    value: "start",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: true,
      },
    ],
    options: [
      {
        name: "--all",
        type: "flag",
        description: "Starts all of the canisters configured in the dfx.json file",
      },
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "status",
    value: "status",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: true,
      },
    ],
    options: [
      {
        name: "--impersonate",
        placeholder: "Principal",
        type: "argument",
        description: "Send request on behalf of the specified principal. This option only works for a local PocketIC instance",
      },
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--all",
        type: "flag",
        description: "Returns status information for all of the canisters configured in the dfx.json file",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "stop",
    value: "stop",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: true,
      },
    ],
    options: [
      {
        name: "--all",
        type: "flag",
        description: "Stops all of the canisters configured in the dfx.json file",
      },
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "uninstall-code",
    value: "uninstall-code",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: true,
      },
    ],
    options: [
      {
        name: "--all",
        type: "flag",
        description: "Uninstalls all of the canisters configured in the dfx.json file",
      },
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "update-settings",
    value: "update-settings",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: true,
      },
    ],
    options: [
      {
        name: "--all",
        type: "flag",
        description: "Updates the settings of all canisters configured in the project dfx.json files",
      },
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--set-controller",
        placeholder: "Identity name or principal",
        type: "argument",
        description: "Specifies the identity name or the principal of the new controller",
      },
      {
        name: "--add-controller",
        placeholder: "Principal",
        type: "argument",
        description: "Add a principal to the list of controllers of the canister",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--remove-controller",
        placeholder: "Principal",
        type: "argument",
        description: "Removes a principal from the list of controllers of the canister",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--compute-allocation",
        placeholder: "0-100",
        type: "argument",
        description: "Specifies the canister's compute allocation. This should be a percent in the range [0..100]",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--memory-allocation",
        placeholder: "0-12 GiB",
        type: "argument",
        description: "Specifies how much memory the canister is allowed to use in total",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
      {
        name: "--freezing-threshold",
        placeholder: "Seconds",
        type: "argument",
        description: "Sets the freezing_threshold in SECONDS",
      },
      {
        name: "--reserved-cycles-limit",
        placeholder: "Cycles",
        type: "argument",
        description: "Sets the upper limit of the canister's reserved cycles balance",
      },
      {
        name: "--wasm-memory-limit",
        placeholder: "Bytes",
        type: "argument",
        description: "Sets a soft limit on the Wasm memory usage of the canister",
      },
      {
        name: "--wasm-memory-threshold",
        placeholder: "Bytes",
        type: "argument",
        description: "Specifies a threshold on the Wasm memory usage of the canister",
      },
      {
        name: "--log-visibility",
        placeholder: "controllers|public",
        type: "argument",
        description: "Specifies who is allowed to read the canister's logs",
      },
      {
        name: "--add-log-viewer",
        placeholder: "Principal",
        type: "argument",
        description: "Add a principal to the list of log viewers of the canister",
      },
      {
        name: "--remove-log-viewer",
        placeholder: "Principal",
        type: "argument",
        description: "Removes a principal from the list of log viewers of the canister",
      },
      {
        name: "--set-log-viewer",
        placeholder: "Principal",
        type: "argument",
        description: "Specifies the the principal of the log viewer of the canister",
      },
      {
        name: "--confirm-very-long-freezing-threshold",
        type: "flag",
        description: "Freezing thresholds above ~1.5 years require this flag as confirmation",
      },
      {
        name: "--yes",
        type: "flag",
        description: "Skips yes/no checks by answering 'yes'. Such checks can result in loss of control, so this is not recommended outside of CI",
      },
      {
        name: "--impersonate",
        placeholder: "Principal",
        type: "argument",
        description: "Send request on behalf of the specified principal. This option only works for a local PocketIC instance",
      },
    ],
  },
  {
    label: "logs",
    value: "logs",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: false,
      },
    ],
    options: [
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
  {
    label: "url",
    value: "url",
    args: [
      {
        name: "CANISTER",
        placeholder: "Enter canister name/id",
        optional: false,
      },
    ],
    options: [
      {
        name: "--network",
        placeholder: "http://localhost:12345/",
        type: "argument",
        description: "Override the compute network to connect to",
      },
      {
        name: "--verbose",
        type: "flag",
        description: "Displays detailed information about operations",
      },
      {
        name: "--playground",
        type: "flag",
        description: "Shorthand for --network=playground. Borrows short-lived canisters on the real IC network",
      },
      {
        name: "--quiet",
        type: "flag",
        description: "Suppresses informational messages",
      },
      {
        name: "--ic",
        type: "flag",
        description: "Shorthand for --network=ic",
      },
      {
        name: "--log",
        placeholder: "stderr",
        type: "argument",
        description: "The logging mode to use. You can log to stderr, a file, or both",
      },
      {
        name: "--logfile",
        placeholder: "path/to/logfile",
        type: "argument",
        description: "The file to log to, if logging to a file",
      },
      {
        name: "--wallet",
        placeholder: "Wallet canister id",
        type: "argument",
        description: "Specify a wallet canister id to perform the call",
      },
      {
        name: "--identity",
        placeholder: "Identity name",
        type: "argument",
        description: "The user identity to run this command as",
      },
      {
        name: "--provisional-create-canister-effective-canister-id",
        placeholder: "Principal",
        type: "argument",
        description: "The effective canister id for provisional canister creation",
      },
    ],
  },
]; 